language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"
  - "pypy3"

jobs:
  include:
    - name: "Linux wheels"
      services:
        - "docker"
      python: "3.8"
      install:
        - "make jq.c"
        - python3 -m pip install cibuildwheel==1.3.0
      script:
        - python3 -m cibuildwheel --output-dir wheelhouse

    - name: "OS X wheels"
      os: osx
      osx_image: xcode11.2
      language: "shell"
      install:
        - "pip install virtualenv"
        - "make jq.c"
        - python3 -m pip install cibuildwheel==1.3.0
      script:
        - python3 -m cibuildwheel --output-dir wheelhouse

install:
  - "make jq.c"
  - "pip install tox"
script: tox -e py
