language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"
  - "pypy3"

jobs:
  include:
    - name: "Linux wheels"
      services:
        - "docker"
      python: "3.8"
      install:
        - python3 -m pip install cibuildwheel==1.3.0 twine virtualenv
        - "make jq.c"
      script:
        - python3 -m cibuildwheel --output-dir wheelhouse
        - twine check wheelhouse/*

    - name: "OS X wheels"
      os: osx
      osx_image: xcode11.2
      language: "shell"
      install:
        - python3 -m pip install cibuildwheel==1.3.0 twine virtualenv
        - "make jq.c"
      script:
        - python3 -m cibuildwheel --output-dir wheelhouse
        - twine check wheelhouse/*

    - name: "Windows wheels"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
      install:
        - python -m pip install cibuildwheel==1.3.0 twine virtualenv
        - python -m pip install cython==0.29.16
        - cython jq.pyx
        - python -m pip install requests certifi
      script:
        - export CIBW_BEFORE_BUILD='pip install requests certifi'
        - python -m cibuildwheel --output-dir wheelhouse
        - twine check wheelhouse/*

install:
  - "make jq.c"
  - "pip install tox"
script: tox -e py
